/* Revisión del cliente · 9 oct 2026. Se carga después de content*.js y templates2.js y aplica los cambios sin tocar los archivos base. */
(function(){
  var EC="https://ecrepro.com/wp-content/uploads/2023/03/logo-ok-png-blanc-electronicacar-300x60.png", ER="https://ecrepro.com/wp-content/uploads/2023/03/Logo-ECREPRO-web.png";
  var NEW={"placa-micro": "https://d8j0ntlcm91z4.cloudfront.net/user_3HOkvdzr5JF7NIsKEGEzCqDg7mK/hf_20261009_112635_2c424812-2afe-46b3-afe4-ee8be8d13cd1.png", "placa-flash": "https://d8j0ntlcm91z4.cloudfront.net/user_3HOkvdzr5JF7NIsKEGEzCqDg7mK/hf_20261009_112637_3bbd99db-9bf6-4049-b9a6-2f4820c48a8b.png", "placa-eeprom": "https://d8j0ntlcm91z4.cloudfront.net/user_3HOkvdzr5JF7NIsKEGEzCqDg7mK/hf_20261009_112635_65c4b0d4-03c7-4bbf-b438-66963f4d6d40.png", "placa-conector": "https://d8j0ntlcm91z4.cloudfront.net/user_3HOkvdzr5JF7NIsKEGEzCqDg7mK/hf_20261009_112639_f917023e-5a79-4edf-a90d-539fedd2ba60.png", "placa-otros": "https://d8j0ntlcm91z4.cloudfront.net/user_3HOkvdzr5JF7NIsKEGEzCqDg7mK/hf_20261009_112636_b7be220b-f5df-4e4d-92fd-7e8105de070f.png", "mem-externa": "https://d8j0ntlcm91z4.cloudfront.net/user_3HOkvdzr5JF7NIsKEGEzCqDg7mK/hf_20261009_112636_38f40612-8969-4219-ad6f-44e8e24d45ee.png", "mem-interna": "https://d8j0ntlcm91z4.cloudfront.net/user_3HOkvdzr5JF7NIsKEGEzCqDg7mK/hf_20261009_112636_803b4865-37d4-465c-baa3-370a1b753e62.png", "mem-emulada": "https://d8j0ntlcm91z4.cloudfront.net/user_3HOkvdzr5JF7NIsKEGEzCqDg7mK/hf_20261009_112636_97aad59e-cc4e-4353-8a56-1158ffe78d08.png", "portada": "https://d8j0ntlcm91z4.cloudfront.net/user_3HOkvdzr5JF7NIsKEGEzCqDg7mK/hf_20261009_112637_9231a230-b97f-4abc-971d-592868f2e906.png", "obd": "https://d8j0ntlcm91z4.cloudfront.net/user_3HOkvdzr5JF7NIsKEGEzCqDg7mK/hf_20261009_113050_530c341a-ed6b-4aa7-b663-b9ccbd42cf45.png"};
  /* 1. Fotos nuevas por URL (tienen prioridad sobre el archivo local antiguo) */
  function fix(list){ list.forEach(function(s){ if(s.img && NEW[s.img]){ s.remote=NEW[s.img]; s.img=s.img+'-v2'; } if(s.items) s.items.forEach(function(it){ if(it.img && NEW[it.img]){ it.remote=NEW[it.img]; it.img=it.img+'-v2'; } }); }); }
  fix(SLIDES); Object.keys(EXTRA).forEach(function(k){ fix(EXTRA[k]); });
  /* 2. Portada sin retrato */
  var cov=SLIDES.find(function(s){return s.type==='cover'}); if(cov){ delete cov.cut; }
  /* 3. Bloque 2 · evaluación reformulada */
  var q2=SLIDES.find(function(s){return s.type==='quiz'&&s.block===2}); if(q2) q2.items=[{q:'¿Qué diferencia hay entre un sensor y un actuador?',a:'El sensor informa a la ECU de lo que ocurre; el actuador ejecuta lo que la ECU ordena.'},{q:'¿Qué diferencia hay entre el software y la calibración?',a:'El software define cómo funciona la ECU; la calibración aporta los valores y los límites con los que trabaja.'},{q:'¿Una lectura virtual sirve para clonar una ECU?',a:'No. Viene del servidor y puede no incluir los datos particulares ni todas las memorias de esa unidad.'},{q:'Si una ECU es EDC17, ¿ya sabemos qué protocolo usar?',a:'No. EDC17 es una familia con muchas variantes; hace falta la referencia exacta de hardware y software.'},{q:'¿Por qué comparamos la etiqueta de la ECU con la identificación electrónica?',a:'Para confirmar que la unidad es la que creemos y detectar diferencias o actualizaciones de software.'}];
  /* 4. Bloque 6 · pregunta corregida */
  (EXTRA[6]||[]).forEach(function(s){ if(s.rows) s.rows.forEach(function(r){ if(r[0]==='¿Quién es la ECU?'){ r[0]='¿Cómo identificar la ECU?'; r[1]='Por familia, referencia, hardware, software y variante.'; } }); });
  /* 5. Bloque 3 · vídeo del sistema antiestático */
  var b3=EXTRA[3]||[]; var at=b3.findIndex(function(s){return s.label&&s.label.indexOf('3.7')===0});
  if(at>=0 && !b3.some(function(s){return s.type==='video'})) b3.splice(at,0,{type:'video', label:'3.6b Sistema de seguridad contra electricidad estática',
  kicker:'Bloque 3 · Seguridad', title:'Un sistema de descarga a tierra en el puesto de trabajo',
  lead:'Pulsera antiestática conectada a la toma de tierra del enchufe. Permite descargar la carga acumulada antes de tocar la placa y evitar daños en los componentes.',
  tiktok:'7594866544295906582',
  img:'riesgo-esd-pulsera', remote:'https://d8j0ntlcm91z4.cloudfront.net/user_3HOkvdzr5JF7NIsKEGEzCqDg7mK/hf_20261009_113049_88fe4670-75ba-4c01-aeea-f0177cb3d0a5.png', cap:'Pulsera antiestática con su cable a la toma de tierra',
  bullets:['La descarga puede ser imperceptible y aun así dañar un componente.','La pulsera se conecta a tierra a través del enchufe: solo al pin de tierra, nunca a fase ni neutro.','Se lleva puesta durante toda la manipulación de la ECU abierta.','Se complementa con alfombrilla ESD y evitando ropa que acumule carga.'],
  note:{h:'Regla',t:'Que una ECU siga funcionando después de tocarla sin protección no demuestra que la manipulación haya sido correcta.',dark:true}});
  /* 6. Plantilla de vídeo */
  window.T2=window.T2||{}; var list=function(items){return '<ul>'+items.map(function(i){return '<li>'+i+'</li>'}).join('')+'</ul>'}; var head=function(s){return '<div class="kicker">'+s.kicker+'</div><h2 style="margin-top:14px">'+s.title+'</h2>'+(s.lead?'<p class="lead" style="margin-top:14px">'+s.lead+'</p>':'')};
  window.T2.video=function(s){ return '<section class="slide s-video"><div class="in">'+head(s)+'<div class="videogrid"><div class="tk"><iframe src="https://www.tiktok.com/embed/v2/'+s.tiktok+'" allow="encrypted-media; fullscreen" allowfullscreen loading="lazy" title="Vídeo"></iframe></div><div class="sidecol">'+(s.img?'<figure class="ph" style="height:360px"><img src="assets/img/'+s.img+'.jpg" alt="" data-remote="'+s.remote+'" onerror="if(this.dataset.remote){this.src=this.dataset.remote;delete this.dataset.remote}else{this.parentNode.classList.add(\'missing\')}"><figcaption><em>Foto pendiente</em>'+(s.cap||'')+'</figcaption></figure>':'')+'<div class="box">'+list(s.bullets)+'</div>'+(s.note?'<div class="box '+(s.note.dark?'dark':'')+'"><b>'+s.note.h+'</b>'+s.note.t+'</div>':'')+'</div></div></div></section>'; };
  /* 7. Marca de agua + logos (tras montar el deck) */
  function logos(cls){ return '<span class="logos"><img class="'+cls+'" src="assets/logo-electronicacar.png" alt="ElectrónicaCar" onerror="this.onerror=null;this.src=EC_LOGO"><span class="sep"></span><img class="'+cls+'" src="assets/logo-ecrepro.png" alt="ECREPRO" onerror="this.onerror=null;this.src=ER_LOGO"></span>'; }
  window.EC_LOGO=EC; window.ER_LOGO=ER;
  document.addEventListener('DOMContentLoaded',function(){ setTimeout(function(){
    var deck=document.getElementById('deck'), bar=document.getElementById('bar'); if(!deck||!bar) return;
    var wm=document.createElement('img'); wm.id='wm'; wm.src='assets/logo-ecrepro-paraguay.png'; wm.alt=''; deck.insertBefore(wm,bar);
    bar.insertAdjacentHTML('beforeend',logos('light'));
    var cov=deck.querySelector('.s-cover .meta'); if(cov) cov.insertAdjacentHTML('afterend','<div class="brands">'+logos('')+'</div>');
    var obs=new MutationObserver(function(){ wm.classList.toggle('dark',bar.classList.contains('dark')); }); obs.observe(bar,{attributes:true,attributeFilter:['class']}); wm.classList.toggle('dark',bar.classList.contains('dark'));
  },0); });
  /* 8. Estilos */
  var st=document.createElement('style'); st.textContent="\n/* V\u00eddeo incrustado */\n.s-video .in{padding:88px 128px 110px;height:100%;display:flex;flex-direction:column;gap:22px}\n.videogrid{display:grid;grid-template-columns:420px 1fr;gap:48px;flex:1;min-height:0}\n.tk{background:var(--ink);border-radius:12px;overflow:hidden;position:relative}\n.tk iframe{position:absolute;inset:0;width:100%;height:100%;border:0;background:#000}\n\n/* Marca de agua central y logos */\n#wm{position:absolute;left:50%;top:50%;width:560px;transform:translate(-50%,-50%);opacity:.035;pointer-events:none;z-index:3;filter:grayscale(1) brightness(0)}\n#wm.dark{filter:grayscale(1) brightness(3);opacity:.05}\n#bar .logos{display:flex;align-items:center;gap:26px;margin-left:auto}\n#bar .logos img{height:20px;width:auto;display:block;opacity:.9}\n#bar .logos .sep{width:1px;height:22px;background:currentColor;opacity:.35}\n#bar.dark .logos img.inv{filter:brightness(0) invert(1)}\n#bar:not(.dark) .logos img.light{filter:invert(1) hue-rotate(180deg)}\n.s-cover .brands{display:flex;align-items:center;gap:34px;margin-top:28px}\n.s-cover .brands img{height:34px;width:auto}\n.s-cover .brands .sep{width:1px;height:30px;background:rgba(255,255,255,.4)}\n"; st.textContent+=".s-cover ~ #wm{display:none}.s-video .in{gap:16px;padding:72px 128px 100px}.videogrid{grid-template-columns:380px 1fr;gap:40px}.s-video .ph{height:300px!important}.s-video .sidecol .box{padding:16px 24px}.s-video .sidecol .box ul li,.s-video .sidecol .box{font-size:19px}.s-video .lead{font-size:24px}#bar .logos img{height:18px}";document.head.appendChild(st);
})();
